### ISSUE TITLE
Nachrichten

### ISSUE THREAD

**Issue by Eiamnacken** [proxer/ProxerAndroid#1]
Wenn ich als eingeloggter User auf eine Nachricht zugreifen will, öffnet sich bloß der Webview von Proxer und meldet mir ich wäre nicht eingeloggt. Version ist 0.2.5

**Comment by rubengees** [comment]
Das liegt daran, dass es derzeit noch keine offizielle Api für Nachrichten von Proxer gibt. Es ist zwar in Planung, aber keiner weiß wie weit das fortgeschritten ist.
Wegen dem Anmelden: Ob man angemeldet ist wird über Cookies verwaltet. Die App und eine Webview haben (zwangsweise) getrennte Cookies. Auch da warte ich noch auf eine bessere Api. 
Wenn du dich aber einmal in der Webview angemeldet hast, sollte er sich das merken.

**Comment by Eiamnacken** [comment]
OK vielleicht sollte man dann ein label verbesserung oder Feature anbringen? Wäre ja etwas das man verbessern könnte sobald die api da ist.

**Comment by rubengees** [comment]
Die neue Version unterstützt nun vollwertiges Messaging: https://github.com/proxer/ProxerAndroid/releases/tag/0.4.0
