### ISSUE TITLE
[Chat] Invite from friend list

### ISSUE THREAD

**Issue by Desnoo** [proxer/ProxerAndroid#11]
# Case
According to the [proxer forum](http://proxer.me/forum/anwendungen/374605-opensource-android-proxer-app-fuer-android?start=30) entry this is a feature request by Sakugawa.

## Request
It should be possible to add friends from a list to a new chat or existent chat. 
2 approaches:

1. Suggest friends while typing to invite friends
2. Pick users from a list of friends to invite them to a chat

@rubengees maybe some additional info by you?

**Comment by rubengees** [comment]
That would be nice 👍
We will have to wait though, as there are no friend APIs yet...

Concerning the proposed apporaches:

1. I think that would lead to too much request and we would get blocked by the firewall quickly.
2. This one sounds good. Once we have a friend list screen, each item (=friend) could have a button, to quickly send a message.

Another apporach which is somewhat like 1:

We could show a suggestion list *once*, when navigating to the NewChat screen. This way we would only have one additional request, which should work.

**Comment by rubengees** [comment]
Not going to happen anytime soon, so closing this.
Will reopen when APIs are available.
