### ISSUE TITLE
Broken Player "Code"

### ISSUE THREAD

**Issue by MeikelLP** [proxer/ProxerAndroid#14]
### Environment
* Android 6.0.1
* OnePlus 2
* App Version 1.2.1

### What happend
* An player named "Code" appears and once clicked an empty message appears. Nothing more.

### Steps to reproduce
1. Anime
2. Deadman Wonderland
3. Eng Dub
4. Episode 8

**Comment by rubengees** [comment]
I have checked this and the server somehow sends incorrect data for the hoster. On the website, it also shows nothing meaningful.
I will report this to the team :+1:
