### ISSUE TITLE
Edit rating in UCP

### ISSUE THREAD

**Issue by AUTplayed** [proxer/ProxerAndroid#18]
I am using version: 1.3.1

I would love if you could edit or add the rating of a show or manga in the UCP. 

This is probably already on your todo list, but I just wanted to be sure.

Thanks for your work!

**Comment by rubengees** [comment]
Yes, this is planned. Since there are no apis for anything concerning writing comments, I can't say when it will come though.

**Comment by rubengees** [comment]
This has finally been implemented.

**Comment by AUTplayed** [comment]
awesome, thanks!
