### ISSUE TITLE
Subscribe to anime and manga

### ISSUE THREAD

**Issue by AUTplayed** [proxer/ProxerAndroid#19]
Hi, it's me again..

I just noticed that you can now subscribe to anime and manga and get notified whenever there's a new episode out. I'm not sure for how long this feature has been out, but it would be awesome if the app had it too :)

Thanks

**Comment by rubengees** [comment]
Yes that's quite new and we also have no apis for that yet, but I made an internal ticket for it and will implement it as soon as apis are available. :grin:

**Comment by Bios-Marcel** [comment]
There's already a subscribe button now, I guess this issue can be closed?

**Comment by AUTplayed** [comment]
yes, thank you very much
