### ISSUE TITLE
App startet nur einmal

### ISSUE THREAD

**Issue by cuechan** [proxer/ProxerAndroid#2]
Die App startet nur einmal korrekt. Dannach Erscheint nur die Meldung "Ein unbekannter Fehler ist aufgetreten. [...]".
Erst nachdem ich bei den Android Einstellungen unter Apps die Daten für ProxerMe gelöscht habe, lädt die App wieder. Allerdings auch nur einmal. 

Ich nutze CyanogeMod 10.1 auf Android 4.2.2.

**Comment by rubengees** [comment]
Ja, das ist mir auch schon aufgefallen. Allerdings ist das nur schlecht reproduzierbar...
Gestern Nacht hatte ich es einmal probiert, da trat das Problem auf, heute ging es wieder. Sehr seltsam.

**Comment by rubengees** [comment]
Ich hab eine neue Version veröffentlicht, die möglicherweise das Problem behebt. Probiers mal aus.

**Comment by cuechan** [comment]
Jup funtioniert :)
Danke
