### ISSUE TITLE
Own F-Droid Repo

### ISSUE THREAD

**Issue by Bios-Marcel** [proxer/ProxerAndroid#20]
Hey,

It'd be cool if ProxerAndroid was available in a F-Droid repository, so one doesn't have to use the Google Play Store.

**Comment by rubengees** [comment]
See #16.

**Comment by Bios-Marcel** [comment]
Oh sorry, didn't think about checking the closed issues. Does that rule only count for the official repos though? You can also have custom repos.

**Comment by rubengees** [comment]
Hi, sorry for not answering, totaly forgot about this one.
Sadly we decided against an own f-droid repo. If you do not want to install the version from the Play Store, you can download the releases from GitHub. These are always in sync.
