### ISSUE TITLE
WLAN Erkennung

### ISSUE THREAD

**Issue by Kyusetzu** [proxer/ProxerAndroid#27]
![20191127_125556](https://user-images.githubusercontent.com/20934631/69721567-65e95f80-1115-11ea-9b40-90310bf46767.jpg)
Die WLAN Erkennung scheint mir noch ein wenig buggy zu sein.

Samsung Galaxy S9
Android 9

Neustarten der App oder des Handys hat nichts gebracht.

**Comment by rubengees** [comment]
Hast du eine besondere Umgebung wie VPN oder einen Proxy?

**Comment by MeikelLP** [comment]
Kann das Problem auch nicht repoduzieren 🤔
Hab sowohl ohne VPN als auch mit (NordVPN) versucht.

**Comment by Kyusetzu** [comment]
> Hast du eine besondere Umgebung wie VPN oder einen Proxy?

Benutze AdGuard als Adblocker.

**Comment by rubengees** [comment]
AdGuard scheint so zu funktionieren, dass es ein synthetisches VPN aufspannt, über dass dann Werbung gefiltert wird. Kannst du testweise probieren, ob der Dialog verschwindet wenn du das mal aus hast?

**Comment by Kyusetzu** [comment]
> AdGuard scheint so zu funktionieren, dass es ein synthetisches VPN aufspannt, über das dann Werbung gefiltert wird. Kannst du testweise probieren, ob der Dialog verschwindet wenn du das mal aus hast?

Kann bestätigen, ohne AdGuard verschwindet die Meldung!

**Comment by rubengees** [comment]
Dann ist die Ursache schon mal geklärt, sehr gut. Ich untersuche mal, ob es eine Change gibt, die Netzwerkart trotzdem rauszubekommen.

**Comment by Kyusetzu** [comment]
Scheint mittlerweile keine Probleme mehr mit der WLAN Erkennung zu geben.
Schließe demnach den Thread.
