### ISSUE TITLE
Download or cache manga chapters

### ISSUE THREAD

**Issue by Blaxzter** [proxer/ProxerAndroid#29]
Feature Request:

It would be nice to have a button to download a specific amount of chapters to have them available offline. 
I guess there also comes along some legal repercussions which I'm currently not thinking about.
If it's not possible I would fork it and implement it on my own when I have time.

**Comment by rubengees** [comment]
The app actually had this feature once, but we removed it to keep true to our policy of not having any downloads. We will keep it this way, so sorry, this is not going to be implemented.

If you fork and implement it, please *do not* distribute the app.

**Comment by Blaxzter** [comment]
I thought so that i've seen it before. 
Is there a reason for this policy?

Could you tell me which commit still had it? 
Or is there a easier way to cache a bunch of chapters except to scroll through them. 
(I don't have internet in the underground)

**Comment by MeikelLP** [comment]
AFAIK it's the creed of Proxer to not hurt the Anime/Manga industry of any country. Providing "offline" content is basically giving people direct access to all anime and manga.

Yes you can download them manually from Proxer but you can do that basically anywhere. But that is not the purpose of Proxer. Proxer also removes links to licensed anime in Germany and other related countries (or links the official stream like anime-on-demand).

Please correct me if I am wrong @rubengees 

http://proxer.me/forum/94-neue-animes-und-mangas/355934-informationen-zur-lizenzierung

**Comment by rubengees** [comment]
Basically what @MeikelLP said, thanks. You can look though the releases to find the last one with the feature, but I can't really recommend that, since some functionality will not work because of changed APIs.

Personally I open the chapter before going underground (all pages are loaded sequentially in the background then).
