### ISSUE TITLE
Message caching

### ISSUE THREAD

**Issue by cuechan** [proxer/ProxerAndroid#3]
When I dont have an Internet connection I can't view or write messages. 
So, caching for received messages and queuing for sent messages would be very cool. 
Maybe the same with the news?

Greetings 
Paul

**Comment by rubengees** [comment]
Yup, but would also require some architecture changes I think...

**Comment by rubengees** [comment]
Messages are queued when sent and only one is sent at a time to ensure they are in the correct order.
Regarding caching: This is quite hard with the current messaging API. I will wait for the official one to come out and have a look at it again then.
