### ISSUE TITLE
[Minor] App gone from app store?

### ISSUE THREAD

**Issue by AUTplayed** [proxer/ProxerAndroid#30]
I have android 6.0.1 and it doesn't show me the app on the google play store anymore (none of your devices are supported) but downloading the releases manually still works.

Maybe you misconfigured the min supported version on the playstore?

**Comment by rubengees** [comment]
Weird, I just checked and the store lists the app as "Android 5 or later". What device do you have?

**Comment by AUTplayed** [comment]
I have an oneplus one (2014) A0001, cyanogen 13.1.3 and android 6.0.1

**Comment by MeikelLP** [comment]
@AUTplayed you can upgrade to LineageOS 16 (Android 9) https://download.lineageos.org/bacon

**Comment by rubengees** [comment]
> I have an oneplus one (2014) A0001

Great device, also had it :grin:

Hmm, not sure what causes that. The app is not available in some countries, maybe that's the problem?

**Comment by AUTplayed** [comment]
Yeah I love it, and it still runs very well.

Country location shouldn't be a problem, I've been able to download it before. 

My guess would be that some dependency you have has a required min version, which the play store detects. (Which would make sense since it happened after a new release) Searching online also gave some similar problems that were caused by external dependencies.

**Comment by rubengees** [comment]
I checked in the play store and the device is explicitly listed as supported. The min sdk is also correct. I can also suspect a bug in the play store or google services. Did you try to delete data and cache of the play store?

![Bildschirmfoto von 2020-04-29 16-47-46](https://user-images.githubusercontent.com/8021265/80610409-9ffabc80-8a39-11ea-8d31-6ec0df448bcb.png)
![Bildschirmfoto von 2020-04-29 16-48-39](https://user-images.githubusercontent.com/8021265/80610414-a12be980-8a39-11ea-825f-f73385d8c3f6.png)

**Comment by AUTplayed** [comment]
whack ![](https://i.imgur.com/T6Qu4Qn.png)

**Comment by rubengees** [comment]
Anything new here? There has been a new release since then, did that show up?

**Comment by AUTplayed** [comment]
aha, now it's up again. Weird..
