### ISSUE TITLE
Manga Preview shows the reserved chapter count instead of the actual one

### ISSUE THREAD

**Issue by FelixSab** [proxer/ProxerAndroid#32]
If you go to the manga listing, it shows the count for reserved chapters, instead of the actual count.
This becomes quite annoying, especially when you are looking for newer manga, which are showing 50 chapters, despite only having 3 or so

**Comment by rubengees** [comment]
Yes, absolutely true. This is an inherent limitation of how the api and data is modeled. I have taken this to internal discussion and will change that if possible.
