### ISSUE TITLE
A bookmark appeared twice.

### ISSUE THREAD

**Issue by seyfahni** [proxer/ProxerAndroid#35]
![Screenshot_20200910-085621](https://user-images.githubusercontent.com/8677475/92692584-acc2e180-f344-11ea-80b8-e280ecb6a81e.jpg)
Both solo leveling bookmarks worked, pointing to the same chapter. After I read the chapter and moved my bookmark to the next one both vanished (because I only show unread chapters).

Reloading the bookmarks didn't solve this issue. Now that I changed the bookmarked chapter I can't reproduce the issue, even when changing back the bookmark.

**Comment by MeikelLP** [comment]
From what I've seen: This is a server side issue. I had this issue before but it's on the "web app" as well.

**Comment by seyfahni** [comment]
That seems quite plausible. You can close this issue if you want to, just thought it might be worth reporting.

**Comment by MeikelLP** [comment]
Let's see what @rubengees has to say

**Comment by rubengees** [comment]
Thanks for the report, it's as @MeikelLP says. Nothing the app really can do about this.

**Comment by MeikelLP** [comment]
I mean you could add a `distinct()` of some kind to the list ?

**Comment by rubengees** [comment]
That breaks the pagination, since that is based on the amount of items per Page. If we reduce that by 1 in case of a duplicate, the next page would never be loaded.

You could propably work around that, but I think it's not really worth the effort.
