### ISSUE TITLE
Captcha broken

### ISSUE THREAD

**Issue by FelixSab** [proxer/ProxerAndroid#37]
When I am hitting a request limit, I cannot resolve the captcha and get redirected directly to the 'no firewall entries' page, having to wait several hours for the request limit being canceled.

![image](https://user-images.githubusercontent.com/24910953/98466837-55b97b80-21d2-11eb-92b9-4a417b0020f1.png)
![image](https://user-images.githubusercontent.com/24910953/98466834-4e926d80-21d2-11eb-8da9-24caadf235a1.png)

**Comment by rubengees** [comment]
This is a long standing known issue on the server side. Not much the app can do about it :/

In the next version the app tries to count the requests itself and shows an error before running into the server side limit to make this issue less likely.
