### ISSUE TITLE
Poor performance on app and website

### ISSUE THREAD

**Issue by TheDevGuyMarc** [proxer/ProxerAndroid#38]
Well since yesterday the performance of the website and the app are incredible low. Website needs almost 5 seconds to load the landingpage. App loads faster but doesn't show pages of manga or loads the stream of anime. I tried to fix this with all I can do for my self: deleting cache, closing other tabs, closing other applications, checking my internet performance (wich is great)

**Comment by MeikelLP** [comment]
https://twitter.com/proxerme/status/1339571851559915522

**Comment by rubengees** [comment]
What @MeikelLP said, nothing to do in the app about that. Thanks for the report though!
