### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by DrDDanger** [proxer/ProxerAndroid#39]
Hallo.

So since 2 days i wanna start the proxer.me app on my device (Samsung S20).  But everytime the app crash. I deleted it more than once and installed it again from the PlayStore. I even downloaded it from GitHub but it still crash after i wanna start it. 
So does someone habe and advice how to fix this issue?

**Comment by rubengees** [comment]
This is a bug that happens on reinstallation from the Play Store and is already fixed by f5f5c016b94e4acc62cf0c96376ac0b2e025c752. You can fix it by deleting the app data in the settings.
