### ISSUE TITLE
process bbcode tags in news

### ISSUE THREAD

**Issue by cuechan** [proxer/ProxerAndroid#4]
I Just saw that the bbcode tags are not resolved in the news view. 

`[i]italicized text[/i]` 
Is shown like this:
[i]italicized text[/i]
And not like this:
_italicized text_

Greetings
Paul

**Comment by rubengees** [comment]
Do you have an example?

**Comment by cuechan** [comment]
Well, i took a look again and now the tags are not shown. 
I think it was [this one](https://proxer.me/forum/237/377874#top) (which starts with an italic font).

Maybe someone just forgot to remove the tags in the news message.
