### ISSUE TITLE
Ein unbekanter Fehler ist aufgetreten. Versuche es erneut.

### ISSUE THREAD

**Issue by L0ric0** [proxer/ProxerAndroid#42]
Since the Server 26 (Manga 5) of proxer died over chrismas some manga's can not be seen (Error: `Ein unbekannter Fehler ist aufgetreten. Versuche es erneut`) in the app but in the browser it is visible without a problem.

**Comment by rubengees** [comment]
This is unrelated, we had to remove some manga due to a request from a publisher. The error message in versions <= 1.11.2 is not adjusted, but this has been fixed in cd171e827991d08725bb3cbe929b5af79a28c752.

**Comment by MeikelLP** [comment]
https://proxer.net/forum/18/388678#top
