### ISSUE TITLE
Mark blocked manga in Bookmark Section and Notifications

### ISSUE THREAD

**Issue by kbitGit** [proxer/ProxerAndroid#45]
Ever since the change, that some manga are not available in the app anymore, I always click on a manga, that is not available.
Especially if i get a notification, that a new chapter is available. 

So my question is, if there is a plan to mark those manga in the app or add a filteroption in the bookmark section?

**Comment by rubengees** [comment]
Thanks for the report! This is the same as https://github.com/proxer/ProxerAndroid/issues/44 :slightly_smiling_face:. We are thinking about what to do currently.
