### ISSUE TITLE
Es sind (noch) keine Kapitel verfügbar.

### ISSUE THREAD

**Issue by Kyusetzu** [proxer/ProxerAndroid#48]
Seit einer Weile hab ich das Problem dass ich keine Mangas lesen kann.
Oder eher... Das keine verfügbar sind.
Ob lizenziert oder unlizensiert.
Macht es dezent schwierig alles zu tracken, selbst wenn man sie wo anders liest.
Keine Ahnung ob das known ist oder noch nicht. :(
Jedenfalls geht mir das jetzt schon ne ganze Weile auf den Keks.
Android 10
v1.11.3
![Screenshot_20210303-140729_ProxerMe](https://user-images.githubusercontent.com/20934631/109811017-9bd79680-7c2a-11eb-879c-4afb4f5138b2.png)
![Screenshot_20210303-140720_ProxerMe](https://user-images.githubusercontent.com/20934631/109811026-9d08c380-7c2a-11eb-903e-dd54dfd27e04.png)
![Screenshot_20210303-140251_ProxerMe](https://user-images.githubusercontent.com/20934631/109811027-9da15a00-7c2a-11eb-9599-93ebc440d5a6.png)

**Comment by rubengees** [comment]
Siehe: https://github.com/proxer/ProxerAndroid/issues/44
