### ISSUE TITLE
Die Sicherheitszertifikate sind ungültig. Überprüfe ob es ein Update für die App gibt

### ISSUE THREAD

**Issue by Tanju42** [proxer/ProxerAndroid#53]
Die App geht nicht mehr hab schon die App neu installiert.

Siehe Screenshot:
![Screenshot_20240408_103634_ProxerMe](https://github.com/proxer/ProxerAndroid/assets/16364184/0775cc67-6068-47ce-b1c8-d90abce71eef)

**Comment by rubengees** [comment]
In der neuen Version [1.11.5](https://github.com/proxer/ProxerAndroid/releases/tag/1.11.5) sollte es wieder gehen.

**Comment by Tanju42** [comment]
Danke geht alles!
