### ISSUE TITLE
swipe down in a conversation reloads the conversation

### ISSUE THREAD

**Issue by cuechan** [proxer/ProxerAndroid#7]
Not sure if this is a bug or a feature :grimacing: 
Swiping down when i am at oldest message in a conversation reloads the messages instead of loading older ones from proxer.me.
IIRC in the older versions swiping down loads older messages.

**Comment by rubengees** [comment]
Haha :D
Are the messages already loaded lost?
I am not so sure if this is a bug or not, as it is hard to reproduce.

**Comment by rubengees** [comment]
Does the infinite scrolling for you work?

**Comment by cuechan** [comment]
It looks like nothing happens. The red wheel appears for half a second and thats all. 
After doing it a few times in a row an error show up saying the does not answered in time (i think thats just my shitty internet connection)

**Comment by cuechan** [comment]
Found out that the main problem is having a slow internet connection. 
So when some new messages are already loaded but fetching older failed all messages are going to be discarded. Even the successfully loaded ones.
I think this is related to #3
