### ISSUE TITLE
Remember login data don't work

### ISSUE THREAD

**Issue by cuechan** [proxer/ProxerAndroid#8]
Also sometimes i just got logged out. 
Something like an automatic re-login would be very nice.

**Comment by rubengees** [comment]
"Remember login data" is meant like this: If enabled, the user is (or should :D) automatically re-logged in upon an App restart. If not, the user is logged out if the App is closed.

About the sudden logout: Yes I also experience that sometimes. I'm still investigating on that.

**Comment by rubengees** [comment]
Should be fixed by 5152df3
